---
- name: Install cartridges for CP4D cluster {{ _p_current_cp4d_cluster.project }} using OLM utils
  debug:
    msg: ""

- name: Ensure that OLM utils work directory exists
  file:
    path: /tmp/work
    state: directory

# Always generate the preview script to log what will be done
- name: Generate command preview script to install cartridges
  set_fact:
    _apply_cr_command_script: "{{ lookup('template', 'apply-cr-cartridges.j2') }}"
  vars:
    _p_preview_script: True 

- name: Show apply-cr command to install cartridges
  debug:
    var: _apply_cr_command_script

- name: Generate preview script to install cartridges, logs are in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log
  shell: |
    {{ _apply_cr_command_script }} > {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log 2>&1
  vars:
    _p_preview_script: True

- name: Copy script to {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.sh
  copy:
    src: "/tmp/work/preview.sh"
    dest: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.sh"
    remote_src: True
    mode: u+rwx

- set_fact:
    _cp4d_cartridges_installed_successfully: True

- name: Write cartridge information to file {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridges.json
  copy:
    content: "{{ _cartridges_to_install | default([]) | to_json }}"
    dest: "{{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridges.json"

- name: Logging state of cartridges in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridge-state.log
  shell: |
    {{ role_path }}/files/log-services-installed.sh \
      {{ status_dir }} \
      {{ _p_current_cp4d_cluster.project }}
  async: 86400
  poll: 0
  register: _log_services

- name: Show details of background task to log cartridge state
  debug:
    var: _log_services

- name: Run apply-cr command to install cartridges
  block:
  - name: Generate OLM utils command to install cartridges
    set_fact:
      _apply_cr_command: "{{ lookup('template', 'apply-cr-cartridges.j2') }}"
    vars:
      _p_preview_script: False
  - name: Run apply-cr command to install cartridges, logs are in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log
    shell: |
      {{ _apply_cr_command }} > {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log 2>&1
    register: _install_cartridges_result
    failed_when: False
  - name: Fail if there was an error installing the cartridge(s) using OLM utils
    fail:
      msg: "{{ _install_cartridges_result }}"
    when: 
    - not _cp4d_cartridges_installed_successfully
    - not (cpd_test_cartridges | default(False) | bool)
  - set_fact:
      _cp4d_cartridges_installed_successfully: False
    when: _install_cartridges_result.rc!=0
  when: not _p_use_preview_script

- name: Run shell script to install cartridges, logs are in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log
  shell: |
    {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.sh >> {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log 2>&1
  when: _p_use_preview_script