---
- name: Install cartridges for CP4D cluster {{ _p_current_cp4d_cluster.project }} using OLM utils
  debug:
    msg: ""

- name: Ensure that OLM utils work directory exists
  file:
    path: /tmp/work
    state: directory

- name: Generate OLM utils command to install cartridges
  set_fact:
    _apply_cr_command: "{{ lookup('template', 'apply-cr-cartridges.j2') }}" 

- name: Show apply-cr command
  debug:
    var: _apply_cr_command

- set_fact:
    _cp4d_cartridges_installed_successfully: True

- name: Write cartridge information to file {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridges.json
  copy:
    content: "{{ _cartridges_to_install | default([]) | to_json }}"
    dest: "{{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridges.json"

- name: Starting installation of cartridges, state is in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridge-state.log
  shell: |
    {{ role_path }}/files/log-services-installed.sh \
      {{ status_dir }} \
      {{ _p_current_cp4d_cluster.project }}
  async: 86400
  poll: 0
  register: _log_services

- name: Show details of background task to log cartridge state
  debug:
    var: _log_services

- name: Run apply-cr command to install cartridges, logs are in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log
  shell: |
    {{ _apply_cr_command }} > {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log 2>&1
  register: _install_cartridges_result
  failed_when: False

- set_fact:
    _cp4d_cartridges_installed_successfully: False
  when: _install_cartridges_result.rc!=0

- name: Fail if there was an error installing the cartridge(s) using OLM utils
  fail:
    msg: "{{ _install_cartridges_result }}"
  when: 
  - not _cp4d_cartridges_installed_successfully
  - not (cpd_test_cartridges | default(False) | bool)