---
- name: "Run the custom resource post-processing scripts"
  include_tasks: "{{ _current_cp4d_cartridge.cr_postprocessing_script }}"
  when: 
  - (_current_cp4d_cartridge.cr_postprocessing_script | default('')) != ''
  - (_current_cp4d_cartridge.state | default('installed')) == 'installed'
