---
- name: Check if aws-access-key secret is in the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "aws-access-key"
    secret_group: "{{ environment_name }}" 

- name: Check that aws-access-key secret is present in the vault
  fail:
    msg: "Secret aws-access-key is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if aws-secret-access-key secret is in the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "aws-secret-access-key"
    secret_group: "{{ environment_name }}" 

- name: Check that aws-secret-access-key secret is present in the vault
  fail:
    msg: "Secret aws-secret-access-key is mandatory and was not found in the vault"
  when: secret_value==""

- include_tasks: aws-rosa-validate-variables.yml
  loop: "{{ all_config.openshift | default([]) }}"
  loop_control:
    loop_var: _current_openshift_cluster
  when: _current_openshift_cluster.infrastructure.type  == 'rosa'

- include_tasks: aws-ipi-validate-variables.yml
  loop: "{{ all_config.openshift | default([]) }}"
  loop_control:
    loop_var: _current_openshift_cluster
  when: _current_openshift_cluster.infrastructure.type  == 'self-managed'