---
global_config:
  environment_name: sample
  cloud_platform: existing-ocp

vault:
  vault_type: file-vault
  vault_authentication_type: none

openshift:
- name: "{{ env_id }}"
  ocp_version: "4.10"
  cluster_name: "{{ env_id }}"
  domain_name: ocp410.tec.uk.ibm.com
  openshift_storage:
  - storage_name: rook-ceph
    storage_type: custom
    ocp_storage_class_file: rook-cephfs
    ocp_storage_class_block: rook-ceph-block