---
- name: Get package manifest name for platform operator
  set_fact:
    _cpd_platform: "{{ cartridge_cr | json_query(query) | first }}"
  vars:
    query: >-
      [?olm_utils_name=='cpd_platform']

- name: Obtain packagemanifest {{ _cpd_platform.package_manifest }} for platform operator
  shell: |
    oc get packagemanifest {{ _cpd_platform.package_manifest }} -o jsonpath="{.status.defaultChannel}"
  register: _cpd_platform_package_manifest
  retries: 30
  delay: 10
  until: _cpd_platform_package_manifest.rc==0

- name: Extract default channel for operator
  set_fact:
    _default_channel: "{{ _cpd_platform_package_manifest.stdout }}"

- name: Prepare yaml file for platform operator subscription
  template:
    src: cpd-platform-subscription.j2
    dest: "{{ status_dir }}/cp4d/cpd-operator-subscription.yml"

- name: Create subscription for the platform operator
  command: |
    oc apply -f "{{ status_dir }}/cp4d/cpd-operator-subscription.yml"

- name: Wait for platform subscirptions to be created
  include_tasks: cp4d-wait-platform-subscriptions.yml

- name: Create OpenShift operator subscriptions for each of the selected cp4d cartridges
  include_tasks: cp4d-create-subscription.yml
  loop: "{{ _cartridges_to_install | default([]) }}"
  loop_control:
    loop_var: _current_cp4d_cartridge

- name: Wait for OpenShift operator subscriptions for each of the selected cp4d cartridges
  include_tasks: cp4d-subscriptions-wait.yml
  loop: "{{ _cartridges_to_install | default([]) }}"
  loop_control:
    loop_var: _current_cp4d_cartridge