---
- include_role:
    name: cp4d-variables

# Create Foundational Services project for Cloud Pak for Data
- name: Create OpenShift Project {{ foundational_services_project }} if it does not exist
  shell: 
    oc new-project {{ foundational_services_project }} || true

# Create Operator Group
- name: Generate definition for OperatorGroup
  template:
    src: operator-group.j2
    dest: "{{ status_dir }}/cp4d/operator-group.yml"

- name: Create OperatorGroup
  command: |
    oc apply -f "{{ status_dir }}/cp4d/operator-group.yml"

- include_tasks: cp4d-create-subscriptions.yml
  when: 
  - not (_p_current_cp4d_cluster.olm_utils | default(False) | bool)
  - _p_current_cp4d_cluster.cp4d_version < "4.5.0"

- include_tasks: cp4d-create-subscriptions-olm-utils.yml
  vars:
    _p_use_preview_script: True
  when: 
  - not (_p_current_cp4d_cluster.olm_utils | default(False) | bool)
  - _p_current_cp4d_cluster.cp4d_version >= "4.5.0"

- include_tasks: cp4d-create-subscriptions-olm-utils.yml
  vars:
    _p_use_preview_script: False
  when: (_p_current_cp4d_cluster.olm_utils | default(False) | bool)