---
- name: Download operator case files to {{ status_dir }}/cp4d/case using OLM utils
  debug:
    msg: ""
    
- name: Ensure that OLM utils work directory exists
  file:
    path: /tmp/work
    state: directory

# Always generate the preview script to log what will be done
- name: Generate command preview script to save case files
  set_fact:
    _apply_olm_command_script: "{{ lookup('template', 'apply-olm-case-save.j2') }}"
  vars:
    _p_preview_script: True

- name: Show apply-olm command to download case files
  debug:
    var: _apply_olm_command_script

- name: Generate preview script to download case files, logs are in {{ status_dir }}/log/apply-olm-case-save.log
  shell: |
    {{ _apply_olm_command_script }} > {{ status_dir }}/log/apply-olm-case-save.log 2>&1

- name: Copy script to {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-case-save.sh
  copy:
    src: "/tmp/work/preview.sh"
    dest: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-case-save.sh"
    remote_src: True
    mode: u+rwx

# TODO: Remove step once problem in preview.sh is fixed
- name: Update script to comment out oc patch command (not connected to cluster at this stage)
  replace:
    path: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-case-save.sh"
    regexp: '^oc patch(.*)'
    replace: '#REMOVED: oc patch\1'

- name: Run apply-olm command to download case files
  block:
  - name: Generate OLM command to save case files
    set_fact:
      _apply_olm_command: "{{ lookup('template', 'apply-olm-case-save.j2') }}"
    vars:
      _p_preview_script: False
  - name: Run apply-olm command to download case files, logs are in {{ status_dir }}/log/apply-olm-case-save.log
    shell: |
      {{ _apply_olm_command }} > {{ status_dir }}/log/apply-olm-case-save.log 2>&1
  when: not _p_use_preview_script

- name: Run shell script to download case files, logs are in {{ status_dir }}/log/apply-olm-case-save.log
  shell: |
    {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-case-save.sh >> {{ status_dir }}/log/apply-olm-case-save.log 2>&1
  when: _p_use_preview_script