---
- include_role:
    name: cp4d-variables
    
- set_fact:
    _case_dir: "{{ status_dir }}/cp4d/case"

- name: Create directory {{ _case_dir }} for case files
  file:
    path: "{{ _case_dir }}"
    state: directory

- name: Show current Cloud Pak for Data cluster
  debug:
    var: _p_current_cp4d_cluster

- include_tasks: download-case-online.yml
  when: 
  - not (_p_current_cp4d_cluster.olm_utils | default(False) | bool)
  - _p_current_cp4d_cluster.cp4d_version < "4.5.0"

- include_tasks: download-case-olm-utils.yml
  vars:
    _p_use_preview_script: True
  when: 
  - not (_p_current_cp4d_cluster.olm_utils | default(False) | bool)
  - _p_current_cp4d_cluster.cp4d_version >= "4.5.0"

- include_tasks: download-case-olm-utils.yml
  vars:
    _p_use_preview_script: False
  when: (_p_current_cp4d_cluster.olm_utils | default(False) | bool)
