---
- include_role:
    name: cp4d-variables

- include_tasks: create-catalog-source-case-files.yml
  when: 
  - not (_p_current_cp4d_cluster.olm_utils | default(False) | bool)
  - _p_current_cp4d_cluster.cp4d_version < "4.5.0"

- include_tasks: create-catalog-source-olm-utils.yml
  vars:
    _p_use_preview_script: True
  when: 
  - not (_p_current_cp4d_cluster.olm_utils | default(False) | bool)
  - _p_current_cp4d_cluster.cp4d_version >= "4.5.0"

- include_tasks: create-catalog-source-olm-utils.yml
  vars:
    _p_use_preview_script: False
  when: (_p_current_cp4d_cluster.olm_utils | default(False) | bool)