---
- name: Check if ocp-pullsecret secret is in the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "ocp-pullsecret"
    secret_group: "{{ environment_name }}" 

- name: Check that ocp-pullsecret secret is present in the vault
  fail:
    msg: "Secret ocp-pullsecret is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if ocp-ssh-pub-key secret is in the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "ocp-ssh-pub-key"
    secret_group: "{{ environment_name }}" 

- name: Check that ocp-ssh-pub-key secret is present in the vault
  fail:
    msg: "Secret ocp-ssh-pub-key is mandatory and was not found in the vault"
  when: secret_value==""

