---

# ------------ PREPARATION ------------------------------------------

- debug:
    msg: "Handling CP4I cluster {{ current_cp4i_cluster.project }}"

- set_fact:
    _cpd_accept_licenses: "False"

- set_fact:
    _cpd_accept_licenses: "True"
  when: (cpd_accept_licenses | default(False) | bool) or (current_cp4i_cluster.accept_licenses | default(False) | bool)

- name: Fail if licenses were not accepted
  fail:
    msg: "You must accept the licenses, either in the cp4i object with accept_licenses: True, or by specifying --accept-all-licenses at the command line"
  when: 
  - not (cpd_accept_licenses | default(False) | bool)
  - not (current_cp4i_cluster.accept_licenses | default(False) | bool)

- set_fact:
    _current_openshift_cluster: "{{ all_config.openshift | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='{{ current_cp4i_cluster.openshift_cluster_name }}']

- name: Download and activate OpenShift client for version {{ _current_openshift_cluster.ocp_version }}
  include_role:
    name: openshift-download-client
  vars:
    _p_ocp_version: "{{ _current_openshift_cluster.ocp_version }}"

- name: Login to the OpenShift cluster
  include_role:
    name: openshift-login
  vars:
    _p_openshift_cluster_name: "{{ current_cp4i_cluster.openshift_cluster_name }}"

- name: Get IBM Entitled Registry key
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "ibm_cp_entitlement_key"
    secret_group: "{{ environment_name }}"

- set_fact:
    ibm_cp_entitlement_key: "{{ secret_value }}"

- fail:
    msg: "No image registry name specified for CP4I but cannot pull from entitled registry because of missing entitlement key in vault"
  when: ibm_cp_entitlement_key == "" and (current_cp4i_cluster.image_registry_name | default("")) == ""

- set_fact:
    entitled_auth: "{{ entitled_registry_username }}:{{ ibm_cp_entitlement_key }}"
  when: ibm_cp_entitlement_key != ""

- set_fact:
    use_entitled_registry: False

- name: Use entitled registry if entitlement key available and no image registry name specified
  set_fact:
    use_entitled_registry: True
  when:
  - (current_cp4i_cluster.image_registry_name | default("")) == ""

- name: Connect to private image registry
  include_role: 
    name: connect-private-image-registry
  when:
  - (current_cp4i_cluster.image_registry_name | default("")) != ""

- name: Remove Cloud Pak for Integration directory for generated files
  file:
    path: "{{ status_dir }}/cp4i"
    state: absent

- name: Create Cloud Pak for Integration directory for generated files
  file:
    path: "{{ status_dir }}/cp4i"
    state: directory

- name: Prepare OpenShift cluster for Cloud Pak for Integration
  include_role:
    name: cp4i-prepare-openshift

# ------------ SETTING PROCESSING FACTS -----------------------------

- set_fact:
    _use_case_files: False

- set_fact:
   _use_case_files: True
  when: (current_cp4i_cluster.image_registry_name | default("")) != "" or (current_cp4i_cluster.use_case_files | default(False) | bool)

- set_fact:
    _use_top_level_operator: False

- set_fact:
    _use_top_level_operator: True
  when: (current_cp4i_cluster.use_top_level_operator | default(False) | bool) and not (current_cp4i_cluster.use_case_files | default(False) | bool) 

- set_fact:
    _operators_in_all_namespaces: False

- set_fact:
    _operators_in_all_namespaces: True
  when: (current_cp4i_cluster.operators_in_all_namespaces | default(False) | bool)

# ------------ DOWLOADING CASE FILES, MIRRORING IMAGES --------------

- name: Prepare case files for Cloud Pak for Integration when using private registry or when explicitly using case files
  include_tasks: prepare-cp4i-case-files.yml
  when: _use_case_files

- name: Mirror images for Cloud Pak for Integration to private registry {{ current_cp4i_cluster.image_registry_name }}
  include_tasks: mirror-images-cp4i.yml
  when: 
  - (current_cp4i_cluster.image_registry_name | default("")) != ""
  - ibm_cp_entitlement_key != ""

# ------------ OPENSHIFT OBJECTS ------------------------------------

- name: Get OpenShift storage classes to use for {{ current_cp4i_cluster.project }} and storage class name {{ current_cp4i_cluster.storage_class_name }}
  include_tasks: cp4i-get-storage-classes.yml

- name: Prepare OpenShift project {{ current_cp4i_cluster.project }} for Cloud Pak for Integration
  include_tasks: openshift-prepare-project.yml

- name: Create entitlement key secret
  include_tasks: create-entitlement-key-secret.yml

# ------------ CREATING CATALOG SOURCES -----------------------------

- name: Create catalog sources for entitled registry when not using CASE files
  include_tasks: create-catalog-sources-entitled.yml
  when: not _use_case_files

- name: Create catalog sources when using CASE files
  include_tasks: create-catalog-source-case-file.yml
  loop: "{{ current_cp4i_cluster.instances | default([]) }}"
  loop_control:
    loop_var: current_cp4i_instance
  when: _use_case_files

# ------------ INSTALLING OPERATORS ---------------------------------

- name: Prepare operator group if installing in specific namespace
  include_tasks: prepare-operator-group.yml
  when: not _operators_in_all_namespaces
  
- name: Install operators for each needed instance type
  include_tasks: install-operator.yml
  loop: "{{ current_cp4i_cluster.instances | default([]) }}"
  loop_control:
    loop_var: current_cp4i_instance
  when: not _use_top_level_operator

- name: Install all CP4I operators using top level operator
  include_tasks: install-operators-top-level.yml
  when: _use_top_level_operator

# ------------ PLATFORM NAVIGATOR -----------------------------------

- name: Install Cloud Pak for Integration Platform Navigator
  include_tasks: install-platform-navigator.yml

# ------------ INTEGRATION INSTANCES --------------------------------

- name: Create instances of CP4I capabilities and runtimes
  include_tasks: create-instance.yml
  loop: "{{ current_cp4i_cluster.instances | default([]) }}"
  loop_control:
    loop_var: current_cp4i_instance

# ------------ FINALIZING -------------------------------------------

- name: Add Cloud Pak for Integration route to /etc/hosts for vSphere
  include_tasks: vsphere-configure-etc-hosts.yml
  when: cloud_platform == "vsphere"

- name: Configure CP4I admin password and store in vault
  include_tasks: configure-cpi-admin-password.yml

- name: Output Cloud pak for Integration URL and admin password
  include_role:
    name: cp4i-cluster-show

- name: Ensure the status log folder exists
  file:
    path: "{{status_dir}}/log"
    state: directory
